Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 102, in build
    return await extension.build(additional_hooks=additional_hooks)
  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 96, in build
    available_commands = await self._get_available_commands(
  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 194, in _get_available_commands
    output = await check_output(
  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 129, in check_output
    assert not rc, f'Expected {args} to pass: {stderr_data}'
AssertionError: Expected ['/usr/bin/python3', '-W', 'ignore:setup.py install is deprecated', '-W', 'ignore:easy_install command is deprecated', 'setup.py', '--help-commands'] to pass: Traceback (most recent call last):
  File "/home/steven/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2050, in try_parse
    return packaging.version.Version(name)
  File "/home/steven/.local/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '.egg-info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/steven/ros2_ws/src/robot_interface/setup.py", line 1, in <module>
    from setuptools import setup
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 16, in <module>
    import setuptools.version
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/home/steven/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/home/steven/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/home/steven/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3295, in _initialize_master_working_set
    list(map(working_set.add_entry, sys.path))
  File "/home/steven/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 621, in add_entry
    for dist in find_distributions(entry, True):
  File "/home/steven/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2092, in find_on_path
    path_item_entries = _by_version_descending(filtered)
  File "/home/steven/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2062, in _by_version_descending
    return sorted(names, key=_by_version, reverse=True)
  File "/home/steven/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2060, in _by_version
    return [try_parse(part) for part in parts]
  File "/home/steven/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2060, in <listcomp>
    return [try_parse(part) for part in parts]
  File "/home/steven/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2052, in try_parse
    return packaging.version.Version('0')
  File "/home/steven/.local/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/version.py", line 269, in __init__
    self._version = _Version(
TypeError: Version.__init__.<locals>.<genexpr>() got an unexpected keyword argument 'epoch'

