Traceback (most recent call last):
  File "/home/steven/ros2_ws/src/yolo_pf_realsense/setup.py", line 7, in <module>
    setup(
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 172, in setup
    ok = dist.parse_command_line()
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 474, in parse_command_line
    args = self._parse_command_opts(parser, args)
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/dist.py", line 1107, in _parse_command_opts
    nargs = _Distribution._parse_command_opts(self, parser, args)
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 533, in _parse_command_opts
    cmd_class = self.get_command_class(command)
  File "/home/steven/.local/lib/python3.10/site-packages/setuptools/dist.py", line 952, in get_command_class
    eps = metadata.entry_points(group='distutils.commands', name=command)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1021, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 487, in select
    return self._all.select(**params)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 359, in select
    return EntryPoints(ep for ep in self if ep.matches(**params))
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 359, in <genexpr>
    return EntryPoints(ep for ep in self if ep.matches(**params))
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 231, in matches
    attrs = (getattr(self, param) for param in params)
TypeError: 'dict_keyiterator' object is not callable
